### ISSUE TITLE
Didn't seem to work

### ISSUE THREAD

**Issue by colonnezi** [r0fld4nc3/Stellaris-Exe-Checksum-Patcher#1]
Activated the tool and logged in and tried to force an easy achievment with console commands for testing and was not successful; on game start also not working if not on ironman.

**Comment by r0fld4nc3** [comment]
Hey, 

Again, just to make sure, **all this does is enable Ironman to be played with mods**.
It doesn't enable anything else, or the activation of achievements in non Ironman game modes.

So, with this said, I'm not entirely sure I understand your issue as console isn't enabled in Ironman.

If you patch the executable and play Ironman with mods, you eventually should be receiving achievements normally.

If perhaps this isn't the case, or the game does not launch, delete the patched/modified executable and verify game files with Steam to force it to download an unmodified version. If you have a backed up one (_.orig_) in the folder also delete it. Then patch it again to make sure it only modified the necessary block, and try again.

Hope this helps.

**Comment by Chillsmeit** [comment]
@colonnezi 
You can also check if the patch works by launching the game and check this message **when you enable ironman**.
![stellaris_v62PZatPKU](https://user-images.githubusercontent.com/93094077/204090129-810c081f-099c-42c5-ab90-0ecc4973bacd.png)
