### ISSUE TITLE
New PC player 

### ISSUE THREAD

**Issue by fkkamara** [r0fld4nc3/Stellaris-Exe-Checksum-Patcher#10]
Good day mate I just downloaded this patch do I need to moved it into the stallris folder for it to work?

**Comment by r0fld4nc3** [comment]
Hey, hello. I noticed you closed this but just wanted to note that you don't nee to move the Patcher itself to the stellaris folder. It should place the patched executable in the installation folder automatically and backup the non-patched .exe.
Cheers!

**Comment by fkkamara** [comment]
Thank you mate and I really appreciate your work man

**Comment by fkkamara** [comment]
am not good with coding or modding but if there is any way I could help I
will love to mate
