### ISSUE TITLE
[Request/Question]Tool for other Pdox games?

### ISSUE THREAD

**Issue by lucas-slavic** [r0fld4nc3/Stellaris-Exe-Checksum-Patcher#11]
Hi there!

Thanks you for this great tool, it's very easy to use and works great. 
Any plans to create somethign similiar for Crusader Kings 2 and/or Europa Universalis 4?

Since the engine is the same (iirc), I guess it want be that differrent?

Best wishes!

**Comment by r0fld4nc3** [comment]
Hello @lucas-slavic !

Thank you so much for the kind words ❤️ 

I currently don't have any plans of porting something similar over to Crusader Kings and/or EU4. I want to first focus on reworking some parts of this app, especially the Linux integration as well when I can get to it; unfortunately I haven't had much time to properly dedicate to it yet.

Once I have achieved that, I may think about those other titles, but for now, regrettably, it cannot be in my plans. Sorry about that!

All the best!

**Comment by lucas-slavic** [comment]
many thanks for the fast answer!
don't worry, thats no problem at all. 

I wish you best luck with the Linux version and hope you have for your projects as much time as you need :)

Thanks again for this great piece of software and best wishes!
