### ISSUE TITLE
someone plsease help

### ISSUE THREAD

**Issue by fkkamara** [r0fld4nc3/Stellaris-Exe-Checksum-Patcher#15]
I downloaded this nd unziped it don't know what to do. Any help will be much appreciated

**Comment by r0fld4nc3** [comment]
Hi @fkkamara 

For Windows, ideally you want to go to the [releases](https://github.com/r0fld4nc3/Stellaris-Exe-Checksum-Patcher/releases) page and download the executable. Then simply run it and patch from installation.

If you still prefer to download the source code, you will need Python installed as well as the modules listed in the [requirements.txt](https://github.com/r0fld4nc3/Stellaris-Exe-Checksum-Patcher/blob/main/StellarisChecksumPatcher/requirements.txt). After that, you may open the system console at that directory location and type `python ./main.py`

If the Patcher is having issues with finding the Steam Library or Stellaris installation, please refer to the issue [#14 Patcher sometimes stuck in finding Steam Library](https://github.com/r0fld4nc3/Stellaris-Exe-Checksum-Patcher/issues/14) on how to fix it while I haven't released a proper patch for it.

If instead you are on Unix (Linux/Mac) I am currently working on implementing support for those platforms.
You may try unzipping the source code and navigating the system console to _/StellarisChecksumPatcher_ and running `python ./main.py` and see if it works, however, for native Unix it might not function correctly.

Hope this helps.

**Comment by fkkamara** [comment]
@r0fld4nc3 thanks a lot mate that helps
