### ISSUE TITLE
Check sum is incorrect on Orion 3.6.1

### ISSUE THREAD

**Issue by Eamead** [r0fld4nc3/Stellaris-Exe-Checksum-Patcher#2]
- It was working fine for me before the Orion patch.
- Checksum is being listed as 927b (the correct checksum at the time of this writing is a6c5).
- I am using mods.

I tried to restore the original .exe and run the patcher again, but received the same result. Patcher believes that it was successful.

**Comment by Eamead** [comment]
In attempting to start a new game. It lists that I am able to get achievements. However during my ongoing game, it failed to trigger a few yesterday, perhaps when it updated something triggered somehow...

Thanks for the clarification. I'll start a new game and see if I can get anything to trigger, but likely you are correct and this ticket should be closed.

**Comment by r0fld4nc3** [comment]
That is odd, however, if you are able to launch the game AND play Ironman with mods, after confirming that it says "This game is eligible for achievements", then everything else that may happen, in theory, should be out of scope from this application.

Check perhaps your mods or the criteria for achievements, perhaps something wasn't met entirely and so they did not trigger.

Once you can verify that you are still receiving achievements feel free to close the ticket 🙂

**Comment by Eamead** [comment]
I did manage to get an achievement on a new game. It must have been something related to the update on a save game that already existed.
