### ISSUE TITLE
Patcher stuck

### ISSUE THREAD

**Issue by AdmiralCatface** [r0fld4nc3/Stellaris-Exe-Checksum-Patcher#3]
Patcher sits at [info] getting steam libraries

Tried both methods, tried in and out of the stellaris directory. Been sitting like this for 30 minutes and I dont think its supposed to take that long.

**Comment by r0fld4nc3** [comment]
That's odd.

Maybe it's having some trouble acquiring some paths.

I'm not sure if this could help but if you go to:  `C:\ProgramData\<YOUR_USER>\Apps\Stellaris\ChecksumPatcher` you should see a file named `StellarisChecksumPatcherLog.txt`.

Could you please upload this file so I could see it is throwing an error?

Apart from that,
- Are you using Windows 10/11 ?
- Did you move your steam libraries or perform any manual modification to them?

Hopefully this lets us dig a bit deeper.

In the meanwhile, you could try one of two things:
- Place the Patcher in the install directory of Stellaris and clicking `Patch From Directory`
- Copy the _stellaris.exe_ from the install directory to the Patcher directory and clicking `Patch From Directory`. After, replace the original executable with the newly patched one.

**Comment by AdmiralCatface** [comment]
I have a couple of steam libraries across multiple drives. Stellaris is on H: and I put the patcher in the stellaris directory and patched through directory. 

That path doesn't exist on my drive either, I'm on win10

I'm a little confused about what you're asking me to do. The patcher doesn't have a directory. I tried putting stellaris.exe and the patcher in their own folder but still the same thing.

Now it will produce a stellaris-patched.exe, but it doesn't replace the new one. I'm going to try to just rename it to the normal exe and back up the original and see if that works.

**Comment by r0fld4nc3** [comment]
Ok, so it really is having trouble locating your game install, that is why it is not replacing your original game file.

As you have the `stellaris-patched.exe`, you can simply rename the original one to `stellaris.exe.orig` or something to your liking and paste the patched one in the install folder, then rename it to just `stellaris.exe`.

It is a bit manual but it ought to work.

Again, if you could provide me with the file located in `C:\ProgramData\<YOUR_USER>\Apps\Stellaris\ChecksumPatcher` then maybe it could help me figure out what could be causing it.

**Comment by AdmiralCatface** [comment]
I'm messing around with it right now, but having an issue from another mod that's preventing me from actually testing it. Some mod, despite being deleted, seems to be baked into the game.

And the file path doesn't exist on my computer, so I cant find the file you want me to upload.

**Comment by ivivaitylin** [comment]
I'm also getting the same problem with it just freezing at 'getting available steam libraries'. Here's my patcher log:

[INFO] Patching from game installation.
[INFO] Locating game install...
[INFO] Acquiring Stellaris installation...
[INFO] Getting installation details for game: Stellaris
[INFO] Acquiring Steam installation...
[DEBUG] Reading Registry Key SOFTWARE\WOW6432Node\Valve\Steam
[DEBUG] Connecting to Local Machine registry.
[DEBUG] Retrieved E:\Steam
[INFO] Getting available Steam Libraries...
[DEBUG] Known paths: ['E:\\Steam\\steamapps', 'D:\\Steam\\steamapps']

For reference, the E:\ steam folder is where I have Stellaris installed, and is also the main steam install drive.

Runinng the 'patch from directory' option does create the patched.exe file so I'll replace that, Log for this is pretty much the same:

[INFO] Patching from directory.
[INFO] Loading file Hex.
[INFO] Streaming File Hex Info...
[INFO] Read Finished.
[INFO] Applying Patch...
[INFO] Acquiring Checksum Block...
[DEBUG] Formatting hexadecimal data to working set...
[DEBUG] Condensing chunks...
[DEBUG] Found potential start candidate: ['48', '8B', '12'] starting from 1017214
[DEBUG] Found potential end candidate: ['85', 'C0'] ending at index 1017233
[DEBUG] Search Offset Start: 17
[INFO] Found potential matching sequence.
[DEBUG] (1017214) 488B12488D0D405B9201E833CD72018BF085C0 (2034464)
[INFO] Patching Block...
[DEBUG] Original Block:  488B12488D0D405B9201E833CD72018BF085C0
[DEBUG] Modified Block: 488B12488D0D405B9201E833CD72018BF033C0
[INFO] Writing stellaris-patched.exe to: E:\Steam\steamapps\common\Stellaris
[INFO] PATCH SUCCESSFUL.
[INFO] Locating game install...
[INFO] Acquiring Stellaris installation...
[INFO] Getting installation details for game: Stellaris
[INFO] Acquiring Steam installation...
[DEBUG] Reading Registry Key SOFTWARE\WOW6432Node\Valve\Steam
[DEBUG] Connecting to Local Machine registry.
[DEBUG] Retrieved E:\Steam
[INFO] Getting available Steam Libraries...
[DEBUG] Known paths: ['E:\\Steam\\steamapps', 'D:\\Steam\\steamapps']



Hope some of this helps!

**Comment by r0fld4nc3** [comment]
Hey @ivivaitylin 

Interesting! Thanks for chiming in.

It does seem like it did locate and replace it properly, perhaps it was as simply a problem with rendering the text on screen.

There is something we could go off of now if you would want to have the troubles:
- Remove the patched executable
- Restore/Re-download (via Steam) the original executable
- Perform the patching again (even if it stays stuck in the 'acquiring libraries' section
- After a few seconds of patching (perhaps a total of 1 minute wait) close Patcher and check if achievements are enabled with Ironman and mods

If this is true, it could simply be something blocking the rendering of text onto the Patcher's log window.

Thanks for the bringing the log in! Hope this helps.

**Comment by r0fld4nc3** [comment]
Hi @ivivaitylin 

Thanks for chiming in.

It does seem like it can locate the libraries but yeah, it stops there for some reason.

How long did you wait, for reference? Maybe having steam libraries in 2 different drives/locations is causing issues.

It does generate the patched executable, still, so you can always replace it manually, for now. I'm sorry for the troubles, I will investigate into having multiple available Steam Library paths.

**Comment by ivivaitylin** [comment]
> How long did you wait, for reference? Maybe having steam libraries in 2 different drives/locations is causing issues.

Longest I waited was around 10 minutes I think?

No idea if it's the multiple paths that's causing issues, but happy to help with any troubleshooting you may need, but for now the patched .exe is working so I'm happy.

**Comment by r0fld4nc3** [comment]
@ivivaitylin 

Yes, 10 minutes is quite excessive!

I was quickly iterating here over if multiple Steam library paths could cause any issues but it also doesn't seem to be the case, at least not at first glance...

Well, I'm happy that at least it is working 😀 I will try to keep an eye out for other potential blockers.

Cheers!

**Comment by AdmiralCatface** [comment]
Well not sure why mine isn't working, but just changing the name of the .exe works it seems.

I found the log also, I was still reading the file path where you wrote user and was still trying to find my user name lol

[StellarisChecksumPatcherLog.txt](https://github.com/r0fld4nc3/Stellaris-Exe-Checksum-Patcher/files/10253164/StellarisChecksumPatcherLog.txt)

**Comment by r0fld4nc3** [comment]
@AdmiralCatface 

Ah yeah my bad! I had originally pasted it wrong! Sorry for the confusion!

Yes so it does seem to be patching correctly, as it does with ivivaitylin, however, it seems to get stuck and I do not know exactly why. I will try to keep testing. It should iterate through the different libraries but something must be happening which I haven't yet pinpointed.

Thank you for the input!

**Comment by djjack7** [comment]
I've just registered to write : Thank You! All is work fine to me ;)

**Comment by r0fld4nc3** [comment]
Thank you so much for your kind words @djjack7 ! I really appreciate it!
