### ISSUE TITLE
Getting error trying to install in ubuntu

### ISSUE THREAD

**Issue by colonnezi** [r0fld4nc3/Stellaris-Exe-Checksum-Patcher#4]
i can sucessfully clone the repository to my pc but make command doesn't work.

**Comment by r0fld4nc3** [comment]
@colonnezi That would be because it currently it doesn't support Linux. Right now it's a purely Windows application. I thought about Linux support in the future and would like to eventually get to it, but right now it is not supported.

**Comment by Chillsmeit** [comment]
> i can sucessfully clone the repository to my pc but make command doesn't work.

It works with Bottles or other wine app, but you have to use Stellaris with Proton instead of using the native linux version. So the program can change the hex checksum in the .exe

**Comment by colonnezi** [comment]
> > i can sucessfully clone the repository to my pc but make command doesn't work.
> 
> @colonnezi It works with Bottles or any other wine app, but you have to use Stellaris with Proton instead of using the native Linux version. That way this "patcher" can change the hex checksum in the original game executable

Hi man, thanks for the answer! I'll wait sugar-beet guy support linux as i try to play games natively if possible
