### ISSUE TITLE
The program cannot create this file automatically

### ISSUE THREAD

**Issue by wzvideni** [r0fld4nc3/Stellaris-Exe-Checksum-Patcher#5]
Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "UI\__init__.py", line 11, in <module>
    from utils.global_defines import logger, config_folder, updater, settings
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "utils\global_defines.py", line 25, in <module>
    logger = Logger(is_debug=is_debug, logger_name="StellarisChecksumPatcherLogger")
  File "logger\Logger.py", line 81, in __init__
    file_handler = logging.FileHandler(self.log_file)
  File "logging\__init__.py", line 1146, in __init__
  File "logging\__init__.py", line 1175, in _open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ProgramData\\r0fld4nc3\\Apps\\Stellaris\\ChecksumPatcher\\StellarisChecksumPatcherLog.txt'

I need to manually create the file for this path to run the program, which should be a problem

**Comment by r0fld4nc3** [comment]
Hello @wzvidewo

Thank you for the report!
I apologise for the inconvenience.

Interesting that it would error on this as I tried to make sure that the file would be created if not present. If it wasn't created then it could be a permissions issue.

Regardless, I will change the location from ProgramData to Local AppData, just to be on the safe side as it is more common to house such files there.

Hopefully later today I can push this update.

**Comment by PJTheFellHanded** [comment]
Hi There, any news on the update? getting the same issue as dewo.

**Comment by r0fld4nc3** [comment]
@PJTheFellHanded 

Hey! Yes, good news indeed. I've just implemented the changes and am quickly testing to make sure they don't cause problems.
So far so good, so hopefully within the next few minutes I will have it up!

**Comment by PJTheFellHanded** [comment]
Amazing, I just came across this after trying for 2 days to make achievments work, cannot for the life of me get the checksum to be valid with Ironman, even with reinstalls etc, hoping this will work, plus let me use my UI mods!

**Comment by r0fld4nc3** [comment]
@PJTheFellHanded 

I understand your pains! Theoretically it _should_ work, and I am hoping this is still the case unless they changed something, in which case the problem goes deeper.

I recently also tried getting the **With Thunderous Applause** achievement and that didn't trigger. It prompted me to try it without mods and the vanilla executable and even still it also didn't pop.

Let's cross fingers this little workaround is still valid 🙂

**Comment by PJTheFellHanded** [comment]
I've got faith in you

**Comment by r0fld4nc3** [comment]
@PJTheFellHanded @wzvidewo 

Updated release to [1.0.6](https://github.com/r0fld4nc3/Stellaris-Exe-Checksum-Patcher/releases/tag/v1.0.6)! Hope this fixes the issue! Thank you for bringing it to my attention!

I won't close it in case a relevant issue to this Github Issue creeps up, but if it's all good feel free to close it!

**Comment by PJTheFellHanded** [comment]
Patch works, thank you very much, seeing that sweet green text as opposed to the red feels great.

**Comment by r0fld4nc3** [comment]
Glad to hear it! 😀

**Comment by wzvidewo** [comment]
Great, it's working now, problem solved. I think I'm going to have a good time playing Stellaris this weekend.
