### ISSUE TITLE
Hello, i've forked your project to try port it to linux, any advice?

### ISSUE THREAD

**Issue by colonnezi** [r0fld4nc3/Stellaris-Exe-Checksum-Patcher#6]
I think it will be a fun opportunity to learn a little about code, so i'll try to port it out... If possible, i would want some advice knowing what files i need to edit to make it work.

**Comment by r0fld4nc3** [comment]
Hey @colonnezi Thanks for showing interest. In the latest dev branch I've already started implementing the foundations for Linux support but I need to rearrange a few things to make that work.

While I commend your help I think I would like to do so myself this one time, as it requires shuffling and some substantial changes to accommodate this, which I hadn't planned for in the beginning.

If this changes I'll certainly let you know!

For reference though, most of it comes down to where things end up being saved or referenced to, so dealing a lot with system paths and variables.

**Comment by colonnezi** [comment]
Ok! Enter in contact if you want some help!
