### ISSUE TITLE
Game crash when starting a new game

### ISSUE THREAD

**Issue by nigthmerer** [r0fld4nc3/Stellaris-Exe-Checksum-Patcher#9]
When i try to initiate a new game and click on play the game suddenly crash, i tried with or without mods and the result is the same.
I used both methods "patch from directory" and "pactch from installation" with the patcher in the game files

Here the log sayin it was has finished the operation and i'm on win 10

[INFO] Patching from directory.
 [INFO] Loading file Hex.
 [INFO] Streaming File Hex Info...
 [INFO] Read Finished. 
  [INFO] Applying Patch...
 [INFO] Acquiring Checksum Block...
 [INFO] Found potential matching sequence.
 [INFO] Patching Block...
 [INFO] Writing stellaris-patched.exe to: D:\SteamLibrary\steamapps\common\Stellaris
   [INFO] PATCH SUCCESSFUL.
 [INFO] Backing up original file.
 [INFO] Moving patched file.
   [INFO] Operations finished.

**Comment by r0fld4nc3** [comment]
Hey there @nigthmerer 

I'm sorry to hear that it's crashing on new game, however, I'm fairly certain it's not because of the patcher.

Because 3.10 has just released, a lot of mods haven't been updated and therefore could be causing crashes.

I'd suggesting launching the game without mods and see if it runs without crashing.

**Comment by nigthmerer** [comment]
Hi @r0fld4nc3 

I just tried to initiate a new game without any mods as you have suggested but as soon as i finish the settings for my galaxy and i press play the game crashes.

Is there any logs i can give to help you?

**Comment by r0fld4nc3** [comment]
Hm that's odd.

Could you try going to the game folder, deleting both game executables and verifying files on Steam?

For logs, you can go to `C:\Users\[YOUR_USER]\AppData\Local\r0fld4nc3\Apps\Stellaris\ChecksumPatcher` and there should be a file called `StellarisChecksumPatcherLog.txt`

**Comment by nigthmerer** [comment]
After i deleted and veryfied the files i launched the game without mods, withou the patcher game started as normal and i could play without problem, applying the patcher and using the "patch from directory" game started but can't go past the galaxy slider because game crashes when play is pressed

[StellarisChecksumPatcherLog.txt](https://github.com/r0fld4nc3/Stellaris-Exe-Checksum-Patcher/files/13397634/StellarisChecksumPatcherLog.txt)

**Comment by r0fld4nc3** [comment]
@nigthmerer 

Ok, so I've just tested it by deleting the .exe's and verifying files. Then ran the Patcher with `Patch From Installation` followed by creating new games with and without mods. Both worked without crashes.

I suggest trying to use the other option `Path From Installation` instead of directory. That could be what's causing an issue.

I haven't pushed a new build yet but in the one I'm working on I've even just removed that option entirely.

Could you try that and see if it works?

**Comment by nigthmerer** [comment]
Hi @r0fld4nc3 

I have recreated your steps and used the "Patch From Installation" but couldn't create a new game as it crashed, so i used the originial .exe and managed to create a new game just fine, i tried to move the patcher to another Disk to see if it solve it but to no avail.

**Comment by r0fld4nc3** [comment]
@nigthmerer I'm not sure what could be causing it.

If you want you can also upload the logs from the game so I could take a look, see if we could spot something.
I'll leave this open and ask a friend to also test and see what the results are.

For the game logs, I believe `error.log` could contain relevant information, as well as `game.log` (less certain)

You can find them in `C:\Users\<YOUR_USER>\Documents\Paradox Interactive\Stellaris\logs`

Apologies again for the hassle. It works for me so without being able to reproduce the problem on my end it's harder to debug for sure.

**Comment by nigthmerer** [comment]
Hey @r0fld4nc3 i found the problem

When i moved the game to Disk C: and executed it the windows defender detected the created file trying to change the value and blocked it, adding the file as an exception solved it, i don't know why it didn't show any notification when on disk D:.

I apologize for the inconvenience and hope you have a nice day and thank you for your support and care.

**Comment by r0fld4nc3** [comment]
Ahhhhhhhhhhhh that would be it then! Amazing find! Thank you for posting the solution! Yeah it should've notified you. I'm glad you worked it out in the end!! Superb and happy gaming! :) 

Have a wonderful day too!
